### ISSUE TITLE
To create a public link, set "share=True" in "launch()".

### ISSUE THREAD

**Issue by yangnt** [ToTheBeginning/PuLID#90]
Sorry, experts, I have the following problem, can you help me?

Run on local URL: http://0.0.0.0:7860
IMPORTANT: You are using gradio version 4.19.1, but version 4.29.0 is available, please upgrade.
--------
To create a public link, set "share=True" in "launch()".

**Comment by Vasiliy-b** [comment]
Mmm, i think my issue can be related. So:
When installing from requirements.txt in order to run Pull ID with flux, Gradio is clearly broken.
 
![Screenshot 2024-09-24 111654](https://github.com/user-attachments/assets/0e0c5c76-d8bc-4465-be40-873aac9f8209)

After trying to update Gradio, the interface works properly, but I encounter the following errors:

`/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/PuLID/app_flux.py", line 155, in generate_image
    x = self.ae.decode(x)
  File "/workspace/PuLID/flux/modules/autoencoder.py", line 309, in decode
    return self.decoder(z)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/PuLID/flux/modules/autoencoder.py", line 253, in forward
    h = self.up[i_level].upsample(h)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/PuLID/flux/modules/autoencoder.py", line 104, in forward
    x = nn.functional.interpolate(x, scale_factor=2.0, mode="nearest")
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'`

I'm not shure that is relatet to gradio issues....

**Comment by Zhuangvictor0** [comment]
> Mmm, i think my issue can be related. So: When installing from requirements.txt in order to run Pull ID with flux, Gradio is clearly broken.
> 
> ![Screenshot 2024-09-24 111654](https://private-user-images.githubusercontent.com/76906661/370196268-0e0c5c76-d8bc-4465-be40-873aac9f8209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjk3NDksIm5iZiI6MTcyNzE2OTQ0OSwicGF0aCI6Ii83NjkwNjY2MS8zNzAxOTYyNjgtMGUwYzVjNzYtZDhiYy00NDY1LWJlNDAtODczYWFjOWY4MjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5MTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhOWUwMzliYzljM2M1ZmNlODQ3MGFlZGZkZjU5NjhmMjAxNDc3ZjhiMjBmNGNhYmYyMzViOTg0Y2IzOWU4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KB2sMHyicE_IT5c1P2_ztpDSApAzNmMX8ixzyqS6HhM)
> 
> After trying to update Gradio, the interface works properly, but I encounter the following errors:
> 
> `/usr/local/lib/python3.10/dist-packages/insightface/utils/transform.py:68: FutureWarning: `rcond`` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions. To use the future default and silence this warning we advise to pass ``rcond=None`, to keep using the old, explicitly pass `rcond=-1`. P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4 /usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True). warnings.warn( Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 536, in process_events response = await route_utils.call_process_api( File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 322, in call_process_api output = await app.get_blocks().process_api( File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1935, in process_api result = await self.call_function( File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1520, in call_function prediction = await anyio.to_thread.run_sync( # type: ignore File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 833, in run result = context.run(func, *args) File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 826, in wrapper response = f(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/workspace/PuLID/app_flux.py", line 155, in generate_image x = self.ae.decode(x) File "/workspace/PuLID/flux/modules/autoencoder.py", line 309, in decode return self.decoder(z) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/workspace/PuLID/flux/modules/autoencoder.py", line 253, in forward h = self.up[i_level].upsample(h) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/workspace/PuLID/flux/modules/autoencoder.py", line 104, in forward x = nn.functional.interpolate(x, scale_factor=2.0, mode="nearest") File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3931, in interpolate return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors) RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'`
> 
> I'm not shure that is relatet to gradio issues.... Using Pytorch 2.0.1 on A100 PCIe

same problem, did you solve it?

**Comment by Vasiliy-b** [comment]
> same problem, did you solve it?

Unfortunately, no. Moreover, I don't have a clue about it.

**Comment by ToTheBeginning** [comment]
> Sorry, experts, I have the following problem, can you help me?
> 
> ## Run on local URL: http://0.0.0.0:7860
> IMPORTANT: You are using gradio version 4.19.1, but version 4.29.0 is available, please upgrade.
> To create a public link, set "share=True" in "launch()".

I couldn't find any error messages from the information you provided. Can you provide more details so we can help you solve the problem?

**Comment by ToTheBeginning** [comment]
@Vasiliy-b @Zhuangvictor0 The error is related to the PyTorch version (https://github.com/pytorch/pytorch/issues/86679). Strangely, I found that 2.0.1 is sufficient in some environments, and I have been using this version locally all along. However, when I was preparing the [Hugging Face demo](https://huggingface.co/spaces/yanze/PuLID-FLUX), I found that 2.0.1 would report the same error, after I switched to 2.1.0 and the problem was resolved. You can refer to the [requirements.txt in our Hugging Face demo](https://huggingface.co/spaces/yanze/PuLID-FLUX/blob/main/requirements.txt).

**Comment by Vasiliy-b** [comment]
> @Vasiliy-b @Zhuangvictor0 The error is related to the PyTorch version ([pytorch/pytorch#86679](https://github.com/pytorch/pytorch/issues/86679)). Strangely, I found that 2.0.1 is sufficient in some environments, and I have been using this version locally all along. However, when I was preparing the [Hugging Face demo](https://huggingface.co/spaces/yanze/PuLID-FLUX), I found that 2.0.1 would report the same error, after I switched to 2.1.0 and the problem was resolved. You can refer to the [requirements.txt in our Hugging Face demo](https://huggingface.co/spaces/yanze/PuLID-FLUX/blob/main/requirements.txt).

I initially used version 2.1.0 and encountered the same issue. I then switched to 2.0.1, but I will try using the requirements.txt from the HF demo with PyTorch 2.1.0. Let's see how that goes

**Comment by Vasiliy-b** [comment]
> > @Vasiliy-b @Zhuangvictor0 The error is related to the PyTorch version ([pytorch/pytorch#86679](https://github.com/pytorch/pytorch/issues/86679)). Strangely, I found that 2.0.1 is sufficient in some environments, and I have been using this version locally all along. However, when I was preparing the [Hugging Face demo](https://huggingface.co/spaces/yanze/PuLID-FLUX), I found that 2.0.1 would report the same error, after I switched to 2.1.0 and the problem was resolved. You can refer to the [requirements.txt in our Hugging Face demo](https://huggingface.co/spaces/yanze/PuLID-FLUX/blob/main/requirements.txt).
> 
> I initially used version 2.1.0 and encountered the same issue. I then switched to 2.0.1, but I will try using the requirements.txt from the HF demo with PyTorch 2.1.0. Let's see how that goes

@Zhuangvictor0 that worked, thx!

**Comment by yangnt** [comment]
Thanks for the experts’ reply and support! Thank you again!
Also, will the flux version be open source? It is really good software.

**Comment by gautijha37** [comment]
@Vasiliy-b did you only change the torch version to 2.1.0 to resolve this bug. Or did you use the huggingface requirements.txt instead of the one in github? Can you share your pip freeze?

**Comment by Vasiliy-b** [comment]
> @Vasiliy-b did you only change the torch version to 2.1.0 to resolve this bug. Or did you use the huggingface requirements.txt instead of the one in github? Can you share your pip freeze?

A already shutdown the server with this particalar instance, so pip freeze is not availible. But all works well with huggingface requirements.txt and 2.1.0 torch
